#!/usr/bin/expect
set timeout 60
spawn ssh -o StrictHostKeyChecking=no dmrhospi@162.214.80.27 "cd public_html/hr && php artisan db:seed --class=SuperAdminRoleSeeder --force && php artisan db:seed --class=SuperAdminSeeder --force && php artisan db:seed --class=SubscriptionPlanSeeder --force && php artisan db:seed --class=SettingSeeder --force && php artisan db:seed --class=EmailTemplateSeeder --force"
expect "password:"
send {1012AK$$007ss@}
send "\r"
expect eof
